### ISSUE TITLE
Undo delete not working

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#19]
Undo delete is not working; the button turns gray and the record is still there; note that I was able to undo others but one records.

Got this when inspecting
 raven.js:1297 
PUT https://rayyan-staging.qcri.org/reviews/21/duplicates/30638 400

  | (anonymous) | @ | raven.js:1297
-- | -- | -- | --
  | send | @ | application-486ce90c…d6c0adf85bc.js:8657
  | ajax | @ | application-486ce90c…d6c0adf85bc.js:8209
  | (anonymous) | @ | application-486ce90c…6c0adf85bc.js:13923
  | dispatch | @ | application-486ce90c…d6c0adf85bc.js:3281
  | eventHandle | @ | application-486ce90c…d6c0adf85bc.js:2899
  | d | @ | raven.js:425

**Comment by fabubaker** [comment]
@hammady Can you check staging logs for this action?

**Comment by hammady** [comment]
Bug, check the debug log below.
```
[bc4c1276-dcc1-4a3d-9682-d5ca319a16ce] Exception raised in duplicates#update, undefined method `transaction' for nil:NilClass
/home/app/controllers/duplicates_controller.rb:40:in `update'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:188:in `process_action'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/rendering.rb:30:in `process_action'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'\n/home/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:19:in `process_action'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/rescue.rb:20:in `process_action'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'\n/home/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:126:in `process'\n/home/vendor/bundle/ruby/2.3.0/gems/actionview-5.0.0.1/lib/action_view/rendering.rb:30:in `process'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:190:in `dispatch'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:262:in `dispatch'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:32:in `serve'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:39:in `block in serve'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `each'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `serve'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:725:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'\n/home/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'\n/home/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/bundler/gems/rack-9e73bd1ae7b5/lib/rack/etag.rb:25:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/bundler/gems/rack-9e73bd1ae7b5/lib/rack/conditional_get.rb:38:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/bundler/gems/rack-9e73bd1ae7b5/lib/rack/head.rb:12:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/bundler/gems/rack-9e73bd1ae7b5/lib/rack/session/abstract/id.rb:232:in `context'\n/home/vendor/bundle/ruby/2.3.0/bundler/gems/rack-9e73bd1ae7b5/lib/rack/session/abstract/id.rb:226:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:36:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'\n/home/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'\n/home/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'\n/home/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/bundler/gems/rack-9e73bd1ae7b5/lib/rack/method_override.rb:22:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/bundler/gems/rack-9e73bd1ae7b5/lib/rack/runtime.rb:22:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/bundler/gems/rack-9e73bd1ae7b5/lib/rack/sendfile.rb:111:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/hirefire-resource-0.3.12/lib/hirefire/middleware.rb:41:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/integrations/rack.rb:51:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `public_send'\n/home/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `method_missing'\n/home/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'\n/home/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:562:in `process_client'\n/home/vendor/bundle/ruby/2.3.0/gems/spawnling-2.1.1/lib/patches.rb:70:in `process_client'\n/home/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:658:in `worker_loop'\n/home/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'\n/home/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:132:in `start'\n/home/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/bin/unicorn:126:in `<top (required)>'\n/home/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'\n/home/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<top (required)>'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'\n/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'\n/usr/local/bin/bundle:23:in `load'\n/usr/local/bin/bundle:23:in `<main>'
[bc4c1276-dcc1-4a3d-9682-d5ca319a16ce] Completed 400 Bad Request in 134ms (Views: 0.3ms | ActiveRecord: 29.6ms | Solr: 0.0ms)
```

**Comment by fabubaker** [comment]
@mouradvt04 Any idea on how to replicate? I tried deleting and undoing a bunch of articles but I never got an error.

**Comment by hammady** [comment]
It's currently happening on staging. We can inspect both databases to see what's the root cause.

**Comment by hammady** [comment]
There is a problem in the logic here. This article does have a dedup_result but not belonging to the latest dedup job (obviously because it was deleted and not included in the latest dedup job).
The code retrieves the dedup_result record from the last dedup job.
```
select * from dedup_results where  article_id=30638;
+------+----------------+--------------+--------------+----------+---------------+----------------------------+----------------------------+
| id   | dedup_job_id   | cluster_id   | article_id   | score    | user_action   | created_at                 | updated_at                 |
|------+----------------+--------------+--------------+----------+---------------+----------------------------+----------------------------|
| 3798 | 37             | 438          | 30638        | 0.980231 | 1             | 2019-02-04 19:14:48.022845 | 2019-02-05 07:55:54.662488 |
+------+----------------+--------------+--------------+----------+---------------+----------------------------+----------------------------+

select * from dedup_jobs where review_id=21 order by id desc;
+------+----------+---------+--------------+----------------------------+-------------+------------------+----------------------------+--
--------------------------+------------------+-----------------+------------------------+
| id   | status   | error   | started_at   | finished_at                | review_id   | articles_count   | created_at                 | u
pdated_at                 | clusters_count   | results_count   | rayyan_store_enabled   |
|------+----------+---------+--------------+----------------------------+-------------+------------------+----------------------------+----------------------------+------------------+-----------------+------------------------|
| 55   | finished | <null>  | <null>       | 2019-02-11 11:09:28.045115 | 21          | <null>           | 2019-02-11 11:09:13.101356 | 2019-02-11 11:09:28.045115 | 485              | 1126            | True                   |
| 54   | finished | <null>  | <null>       | 2019-02-11 11:08:08.439955 | 21          | <null>           | 2019-02-11 11:07:53.291177 | 2019-02-11 11:08:08.439955 | 485              | 1126            | True                   |
| 44   | finished | <null>  | <null>       | 2019-02-05 14:00:59.603763 | 21          | <null>           | 2019-02-05 14:00:42.164482 | 2019-02-05 14:00:59.603763 | 485              | 1126            | True                   |
| 43   | finished | <null>  | <null>       | 2019-02-05 13:56:49.25635  | 21          | <null>           | 2019-02-05 13:56:30.169816 | 2019-02-05 13:56:49.25635  | 485              | 1126            | True                   |
| 42   | finished | <null>  | <null>       | 2019-02-05 13:16:05.571065 | 21          | <null>           | 2019-02-05 13:15:46.183136 | 2019-02-05 13:16:05.571065 | 485              | 1126            | True                   |
| 41   | finished | <null>  | <null>       | 2019-02-05 13:11:02.563446 | 21          | <null>           | 2019-02-05 13:10:47.14648  | 2019-02-05 13:11:02.563446 | 485              | 1126            | True                   |
| 40   | finished | <null>  | <null>       | 2019-02-05 09:28:57.183042 | 21          | <null>           | 2019-02-05 09:28:38.850519 | 2019-02-05 09:28:57.183042 | 485              | 1126            | True                   |
| 39   | finished | <null>  | <null>       | 2019-02-05 08:58:29.04162  | 21          | <null>           | 2019-02-05 08:58:10.601428 | 2019-02-05 08:58:29.04162  | 485              | 1125            | True                   |
| 38   | finished | <null>  | <null>       | 2019-02-05 08:35:39.043157 | 21          | <null>           | 2019-02-05 08:35:18.674128 | 2019-02-05 08:35:39.043157 | 475              | 1100            | True                   |
| 37   | finished | <null>  | <null>       | 2019-02-04 19:15:04.370187 | 21          | <null>           | 2019-02-04 19:14:14.004159 | 2019-02-04 19:15:04.370187 | 465              | 1073            | True                   |
| 36   | finished | <null>  | <null>       | 2019-02-04 18:49:46.361522 | 21          | <null>           | 2019-02-04 18:49:44.01825  | 2019-02-04 18:49:46.361522 | <null>           | <null>          | True                   |
+------+----------+---------+--------------+----------------------------+-------------+------------------+----------------------------+----------------------------+------------------+-----------------+------------------------+

select * from dedup_results where dedup_job_id = 55 and article_id=30638;
+------+----------------+--------------+--------------+---------+---------------+--------------+--------------+
| id   | dedup_job_id   | cluster_id   | article_id   | score   | user_action   | created_at   | updated_at   |
|------+----------------+--------------+--------------+---------+---------------+--------------+--------------|
+------+----------------+--------------+--------------+---------+---------------+--------------+--------------+

```

To reproduce, delete a duplicate, rerun a dedup job, then undo the deletion.

**Comment by hammady** [comment]
We will disable undo for now, and brainstorm later on how to restore the old behavior.
