### ISSUE TITLE
Prediction not working for some reviews

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#83]
Ratings cannot be computed for some reviews apparently due to an error from Rayyan Store.
Logging the prediction worker we see:
```
"
[Worker(host:predictor-648dcfb8bb-2pwqz pid:1)] Starting job worker
[Worker(host:predictor-648dcfb8bb-2pwqz pid:1)] Job SvmPredictionModelTrainJob#run (id=161241721) (queue=prediction) RUNNING
[Worker(host:predictor-648dcfb8bb-2pwqz pid:1)] Job SvmPredictionModelTrainJob#run (id=161241721) (queue=prediction) FAILED (3 prior attempts) with RayyanStore::Exception: Error in GET /query [502]: 
2019-09-23T09:14:31+0300: [Worker(host:predictor-648dcfb8bb-2pwqz pid:1)] Job SvmPredictionModelTrainJob#run (id=161241721) (queue=prediction) FAILED (3 prior attempts) with RayyanStore::Exception: Error in GET /query [502]: 
[Worker(host:predictor-648dcfb8bb-2pwqz pid:1)] 1 jobs processed at 0.0774 j/s, 1 failed
[Worker(host:predictor-648dcfb8bb-2pwqz pid:1)] Exiting...
rake aborted!
SignalException: SIGTERM
"
Last_error in the delayed_jobs table is
"
Error in GET /query [502]:                                                                                                                                                |
| /home/vendor/bundle/ruby/2.3.0/gems/rayyan-store-0.1.14/lib/rayyan-store.rb:266:in `request'                                                                              |
| /home/vendor/bundle/ruby/2.3.0/gems/rayyan-store-0.1.14/lib/rayyan-store.rb:278:in `get_request'                                                                          |
| /home/vendor/bundle/ruby/2.3.0/gems/rayyan-store-0.1.14/lib/rayyan-store.rb:72:in `query'                                                                                 |
| /home/app/models/review.rb:635:in `refined_articles_from_rayyan_store'                                                                                                    |
| /home/app/models/review.rb:644:in `refined_articles'                                                                                                                      |
| /home/app/models/prediction_model_train_job.rb:61:in `run'      
"
```

**Comment by fabubaker** [comment]
It's clear that the 502 is coming from the proxy. So we're adding NewRelic instrumentation to it to get some more insights on why a 502 is being returned.

**Comment by hammady** [comment]
I believe this is closed by https://github.com/qcri/rayyan/pull/522. @fabubaker can you please verify and close?
